name: Build and Release

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
  push:
    tags:
      - v*

jobs:
  build-and-release:
    name: Build, Sign and Release APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build APKs
        run: |
          flutter pub get
          flutter build apk --release --tree-shake-icons
          flutter build apk --target-platform android-arm64 --split-per-abi --release --tree-shake-icons
          mkdir -p releases
          mv -f build/app/outputs/flutter-apk/*-release.apk releases
          mv -f releases/app-release.apk releases/app-universal-release.apk

      - name: Sign APKs
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: releases
          fileRegex: .*-release.apk
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APKs
        run: |
          for name in $(ls releases/*-release.apk); do mv -f $name ${name%-release.apk}-signed.apk ; done

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB1_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.TAG }}
          release_name: Release ${{ github.event.inputs.TAG }}
          draft: false
          prerelease: false

      - name: Upload APKs
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: releases/

      - name: Release to GitHub
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "releases/*-signed.apk"
          token: ${{ secrets.GITHUB1_TOKEN }}
          tag: ${{ github.event.inputs.TAG }}
